[package]
publish = false
name = "go-ext-wasm"
version = "0.2.0"
authors = ["Ivan Enderlin <ivan.enderlin@hoa-project.net>"]
edition = "2018"
description = "Go library to run WebAssembly binaries"
readme = "README.md"
repository = "https://github.com/wasmerio/go-ext-wasm"
keywords = ["golang", "extension", "webassembly"]
categories = ["wasm"]

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies.wasmer-runtime]
version = "0.17"
default-features = false
features = ["llvm", "default-backend-llvm"]


[dependencies.wasmer-runtime-c-api]
version = "0.17"
default-features = false
features = ["llvm-backend", "wasi"]
